# ArchiToolkitCppInteropGenConfig.cmake

get_filename_component(ARCHITOOLKIT_CPPINTEROPGEN_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

set(ARCHITOOLKIT_CPPINTEROPGEN_INCLUDE_DIR "${ARCHITOOLKIT_CPPINTEROPGEN_ROOT}/build/native/include")

add_library(ArchiToolkit::CppInteropGen INTERFACE IMPORTED)

set_target_properties(ArchiToolkit::CppInteropGen PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${ARCHITOOLKIT_CPPINTEROPGEN_INCLUDE_DIR}"
)