// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;

#pragma warning disable CS9113 // Parameter is unread.

namespace ArchiToolkit.Grasshopper;

/// <summary>
///     The document objects.
/// </summary>
/// <param name="recognizeName">for localization</param>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Class | AttributeTargets.Struct)]
[Conditional(Constant.KeepAttributes)]
public class DocObjAttribute(string recognizeName = "") : Attribute;

/// <summary>
/// The parameters generated by default. not recommended.
/// </summary>
/// <param name="recognizeName"></param>
/// <typeparam name="T"></typeparam>
[AttributeUsage(AttributeTargets.Assembly)]
[Conditional(Constant.KeepAttributes)]
public class DocObjAttribute<T>(
    string recognizeName = "",
    string name = "",
    string nickName = "",
    string description = "",
    string typeName = "",
    string typeDescription = "") : Attribute;