files:
  - source: src/libraries/ArchiToolkit.Assertions/Resources/AssertionLocalization.resx
    translation: /src/libraries/ArchiToolkit.Assertions/Resources/AssertionLocalization.%two_letters_code%.resx
